# Generated by Django 5.1.7 on 2025-03-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
