# Generated by Django 5.1.7 on 2025-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_comment_like_comment_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
