# Generated by Django 5.1.7 on 2025-03-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_comment_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="like",
            new_name="likes",
        ),
    ]
