# Generated by Django 5.1.7 on 2025-03-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_like_comment_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edited_ad",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
