# Generated by Django 5.1.7 on 2025-03-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_comment_edited_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="edited_ad",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
